// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MemberInput struct {
	DiscordUID string `json:"discord_uid"`
	Email      string `json:"email"`
}

type MemberVerificationInput struct {
	ID                int    `json:"id"`
	VerificationToken string `json:"verification_token"`
}
