// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MemberInput struct {
	Email string `json:"email"`
}

type MemberVerificationInput struct {
	ID                int    `json:"id"`
	VerificationToken string `json:"verification_token"`
}

type VerificationResult struct {
	InviteCode string `json:"invite_code"`
}
