// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (m *MemberQuery) CollectFields(ctx context.Context, satisfies ...string) *MemberQuery {
	if fc := graphql.GetFieldContext(ctx); fc != nil {
		m = m.collectField(graphql.GetOperationContext(ctx), fc.Field, satisfies...)
	}
	return m
}

func (m *MemberQuery) collectField(ctx *graphql.OperationContext, field graphql.CollectedField, satisfies ...string) *MemberQuery {
	return m
}
