// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ymsg19/sfc-guardbot/ent/member"
)

// MemberCreate is the builder for creating a Member entity.
type MemberCreate struct {
	config
	mutation *MemberMutation
	hooks    []Hook
}

// SetDiscordUID sets the "discord_uid" field.
func (mc *MemberCreate) SetDiscordUID(s string) *MemberCreate {
	mc.mutation.SetDiscordUID(s)
	return mc
}

// SetEmail sets the "email" field.
func (mc *MemberCreate) SetEmail(s string) *MemberCreate {
	mc.mutation.SetEmail(s)
	return mc
}

// SetIsVerified sets the "is_verified" field.
func (mc *MemberCreate) SetIsVerified(b bool) *MemberCreate {
	mc.mutation.SetIsVerified(b)
	return mc
}

// SetNillableIsVerified sets the "is_verified" field if the given value is not nil.
func (mc *MemberCreate) SetNillableIsVerified(b *bool) *MemberCreate {
	if b != nil {
		mc.SetIsVerified(*b)
	}
	return mc
}

// SetVerificationExpiry sets the "verification_expiry" field.
func (mc *MemberCreate) SetVerificationExpiry(t time.Time) *MemberCreate {
	mc.mutation.SetVerificationExpiry(t)
	return mc
}

// SetNillableVerificationExpiry sets the "verification_expiry" field if the given value is not nil.
func (mc *MemberCreate) SetNillableVerificationExpiry(t *time.Time) *MemberCreate {
	if t != nil {
		mc.SetVerificationExpiry(*t)
	}
	return mc
}

// SetHashedVerificationToken sets the "hashed_verification_token" field.
func (mc *MemberCreate) SetHashedVerificationToken(b []byte) *MemberCreate {
	mc.mutation.SetHashedVerificationToken(b)
	return mc
}

// SetVerificationTokenExpiry sets the "verification_token_expiry" field.
func (mc *MemberCreate) SetVerificationTokenExpiry(t time.Time) *MemberCreate {
	mc.mutation.SetVerificationTokenExpiry(t)
	return mc
}

// SetNillableVerificationTokenExpiry sets the "verification_token_expiry" field if the given value is not nil.
func (mc *MemberCreate) SetNillableVerificationTokenExpiry(t *time.Time) *MemberCreate {
	if t != nil {
		mc.SetVerificationTokenExpiry(*t)
	}
	return mc
}

// Mutation returns the MemberMutation object of the builder.
func (mc *MemberCreate) Mutation() *MemberMutation {
	return mc.mutation
}

// Save creates the Member in the database.
func (mc *MemberCreate) Save(ctx context.Context) (*Member, error) {
	var (
		err  error
		node *Member
	)
	mc.defaults()
	if len(mc.hooks) == 0 {
		if err = mc.check(); err != nil {
			return nil, err
		}
		node, err = mc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MemberMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = mc.check(); err != nil {
				return nil, err
			}
			mc.mutation = mutation
			if node, err = mc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(mc.hooks) - 1; i >= 0; i-- {
			if mc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MemberCreate) SaveX(ctx context.Context) *Member {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mc *MemberCreate) Exec(ctx context.Context) error {
	_, err := mc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mc *MemberCreate) ExecX(ctx context.Context) {
	if err := mc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mc *MemberCreate) defaults() {
	if _, ok := mc.mutation.IsVerified(); !ok {
		v := member.DefaultIsVerified
		mc.mutation.SetIsVerified(v)
	}
	if _, ok := mc.mutation.VerificationExpiry(); !ok {
		v := member.DefaultVerificationExpiry()
		mc.mutation.SetVerificationExpiry(v)
	}
	if _, ok := mc.mutation.VerificationTokenExpiry(); !ok {
		v := member.DefaultVerificationTokenExpiry()
		mc.mutation.SetVerificationTokenExpiry(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mc *MemberCreate) check() error {
	if _, ok := mc.mutation.DiscordUID(); !ok {
		return &ValidationError{Name: "discord_uid", err: errors.New(`ent: missing required field "Member.discord_uid"`)}
	}
	if v, ok := mc.mutation.DiscordUID(); ok {
		if err := member.DiscordUIDValidator(v); err != nil {
			return &ValidationError{Name: "discord_uid", err: fmt.Errorf(`ent: validator failed for field "Member.discord_uid": %w`, err)}
		}
	}
	if _, ok := mc.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Member.email"`)}
	}
	if v, ok := mc.mutation.Email(); ok {
		if err := member.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Member.email": %w`, err)}
		}
	}
	if _, ok := mc.mutation.IsVerified(); !ok {
		return &ValidationError{Name: "is_verified", err: errors.New(`ent: missing required field "Member.is_verified"`)}
	}
	if _, ok := mc.mutation.VerificationExpiry(); !ok {
		return &ValidationError{Name: "verification_expiry", err: errors.New(`ent: missing required field "Member.verification_expiry"`)}
	}
	if _, ok := mc.mutation.HashedVerificationToken(); !ok {
		return &ValidationError{Name: "hashed_verification_token", err: errors.New(`ent: missing required field "Member.hashed_verification_token"`)}
	}
	if v, ok := mc.mutation.HashedVerificationToken(); ok {
		if err := member.HashedVerificationTokenValidator(v); err != nil {
			return &ValidationError{Name: "hashed_verification_token", err: fmt.Errorf(`ent: validator failed for field "Member.hashed_verification_token": %w`, err)}
		}
	}
	if _, ok := mc.mutation.VerificationTokenExpiry(); !ok {
		return &ValidationError{Name: "verification_token_expiry", err: errors.New(`ent: missing required field "Member.verification_token_expiry"`)}
	}
	return nil
}

func (mc *MemberCreate) sqlSave(ctx context.Context) (*Member, error) {
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (mc *MemberCreate) createSpec() (*Member, *sqlgraph.CreateSpec) {
	var (
		_node = &Member{config: mc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: member.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: member.FieldID,
			},
		}
	)
	if value, ok := mc.mutation.DiscordUID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: member.FieldDiscordUID,
		})
		_node.DiscordUID = value
	}
	if value, ok := mc.mutation.Email(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: member.FieldEmail,
		})
		_node.Email = value
	}
	if value, ok := mc.mutation.IsVerified(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: member.FieldIsVerified,
		})
		_node.IsVerified = value
	}
	if value, ok := mc.mutation.VerificationExpiry(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: member.FieldVerificationExpiry,
		})
		_node.VerificationExpiry = value
	}
	if value, ok := mc.mutation.HashedVerificationToken(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBytes,
			Value:  value,
			Column: member.FieldHashedVerificationToken,
		})
		_node.HashedVerificationToken = value
	}
	if value, ok := mc.mutation.VerificationTokenExpiry(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: member.FieldVerificationTokenExpiry,
		})
		_node.VerificationTokenExpiry = value
	}
	return _node, _spec
}

// MemberCreateBulk is the builder for creating many Member entities in bulk.
type MemberCreateBulk struct {
	config
	builders []*MemberCreate
}

// Save creates the Member entities in the database.
func (mcb *MemberCreateBulk) Save(ctx context.Context) ([]*Member, error) {
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Member, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *MemberCreateBulk) SaveX(ctx context.Context) []*Member {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcb *MemberCreateBulk) Exec(ctx context.Context) error {
	_, err := mcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcb *MemberCreateBulk) ExecX(ctx context.Context) {
	if err := mcb.Exec(ctx); err != nil {
		panic(err)
	}
}
