// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ymsg19/sfc-guardbot/ent/member"
	"github.com/ymsg19/sfc-guardbot/ent/predicate"
)

// MemberUpdate is the builder for updating Member entities.
type MemberUpdate struct {
	config
	hooks    []Hook
	mutation *MemberMutation
}

// Where appends a list predicates to the MemberUpdate builder.
func (mu *MemberUpdate) Where(ps ...predicate.Member) *MemberUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetIsVerified sets the "is_verified" field.
func (mu *MemberUpdate) SetIsVerified(b bool) *MemberUpdate {
	mu.mutation.SetIsVerified(b)
	return mu
}

// SetNillableIsVerified sets the "is_verified" field if the given value is not nil.
func (mu *MemberUpdate) SetNillableIsVerified(b *bool) *MemberUpdate {
	if b != nil {
		mu.SetIsVerified(*b)
	}
	return mu
}

// SetVerificationExpiry sets the "verification_expiry" field.
func (mu *MemberUpdate) SetVerificationExpiry(t time.Time) *MemberUpdate {
	mu.mutation.SetVerificationExpiry(t)
	return mu
}

// SetNillableVerificationExpiry sets the "verification_expiry" field if the given value is not nil.
func (mu *MemberUpdate) SetNillableVerificationExpiry(t *time.Time) *MemberUpdate {
	if t != nil {
		mu.SetVerificationExpiry(*t)
	}
	return mu
}

// SetHashedVerificationToken sets the "hashed_verification_token" field.
func (mu *MemberUpdate) SetHashedVerificationToken(b []byte) *MemberUpdate {
	mu.mutation.SetHashedVerificationToken(b)
	return mu
}

// SetVerificationTokenExpiry sets the "verification_token_expiry" field.
func (mu *MemberUpdate) SetVerificationTokenExpiry(t time.Time) *MemberUpdate {
	mu.mutation.SetVerificationTokenExpiry(t)
	return mu
}

// SetNillableVerificationTokenExpiry sets the "verification_token_expiry" field if the given value is not nil.
func (mu *MemberUpdate) SetNillableVerificationTokenExpiry(t *time.Time) *MemberUpdate {
	if t != nil {
		mu.SetVerificationTokenExpiry(*t)
	}
	return mu
}

// Mutation returns the MemberMutation object of the builder.
func (mu *MemberUpdate) Mutation() *MemberMutation {
	return mu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MemberUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mu.hooks) == 0 {
		if err = mu.check(); err != nil {
			return 0, err
		}
		affected, err = mu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MemberMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = mu.check(); err != nil {
				return 0, err
			}
			mu.mutation = mutation
			affected, err = mu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mu.hooks) - 1; i >= 0; i-- {
			if mu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MemberUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MemberUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MemberUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mu *MemberUpdate) check() error {
	if v, ok := mu.mutation.HashedVerificationToken(); ok {
		if err := member.HashedVerificationTokenValidator(v); err != nil {
			return &ValidationError{Name: "hashed_verification_token", err: fmt.Errorf(`ent: validator failed for field "Member.hashed_verification_token": %w`, err)}
		}
	}
	return nil
}

func (mu *MemberUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   member.Table,
			Columns: member.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: member.FieldID,
			},
		},
	}
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.IsVerified(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: member.FieldIsVerified,
		})
	}
	if value, ok := mu.mutation.VerificationExpiry(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: member.FieldVerificationExpiry,
		})
	}
	if value, ok := mu.mutation.HashedVerificationToken(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBytes,
			Value:  value,
			Column: member.FieldHashedVerificationToken,
		})
	}
	if value, ok := mu.mutation.VerificationTokenExpiry(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: member.FieldVerificationTokenExpiry,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{member.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// MemberUpdateOne is the builder for updating a single Member entity.
type MemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MemberMutation
}

// SetIsVerified sets the "is_verified" field.
func (muo *MemberUpdateOne) SetIsVerified(b bool) *MemberUpdateOne {
	muo.mutation.SetIsVerified(b)
	return muo
}

// SetNillableIsVerified sets the "is_verified" field if the given value is not nil.
func (muo *MemberUpdateOne) SetNillableIsVerified(b *bool) *MemberUpdateOne {
	if b != nil {
		muo.SetIsVerified(*b)
	}
	return muo
}

// SetVerificationExpiry sets the "verification_expiry" field.
func (muo *MemberUpdateOne) SetVerificationExpiry(t time.Time) *MemberUpdateOne {
	muo.mutation.SetVerificationExpiry(t)
	return muo
}

// SetNillableVerificationExpiry sets the "verification_expiry" field if the given value is not nil.
func (muo *MemberUpdateOne) SetNillableVerificationExpiry(t *time.Time) *MemberUpdateOne {
	if t != nil {
		muo.SetVerificationExpiry(*t)
	}
	return muo
}

// SetHashedVerificationToken sets the "hashed_verification_token" field.
func (muo *MemberUpdateOne) SetHashedVerificationToken(b []byte) *MemberUpdateOne {
	muo.mutation.SetHashedVerificationToken(b)
	return muo
}

// SetVerificationTokenExpiry sets the "verification_token_expiry" field.
func (muo *MemberUpdateOne) SetVerificationTokenExpiry(t time.Time) *MemberUpdateOne {
	muo.mutation.SetVerificationTokenExpiry(t)
	return muo
}

// SetNillableVerificationTokenExpiry sets the "verification_token_expiry" field if the given value is not nil.
func (muo *MemberUpdateOne) SetNillableVerificationTokenExpiry(t *time.Time) *MemberUpdateOne {
	if t != nil {
		muo.SetVerificationTokenExpiry(*t)
	}
	return muo
}

// Mutation returns the MemberMutation object of the builder.
func (muo *MemberUpdateOne) Mutation() *MemberMutation {
	return muo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MemberUpdateOne) Select(field string, fields ...string) *MemberUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Member entity.
func (muo *MemberUpdateOne) Save(ctx context.Context) (*Member, error) {
	var (
		err  error
		node *Member
	)
	if len(muo.hooks) == 0 {
		if err = muo.check(); err != nil {
			return nil, err
		}
		node, err = muo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MemberMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = muo.check(); err != nil {
				return nil, err
			}
			muo.mutation = mutation
			node, err = muo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(muo.hooks) - 1; i >= 0; i-- {
			if muo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = muo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, muo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MemberUpdateOne) SaveX(ctx context.Context) *Member {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MemberUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MemberUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (muo *MemberUpdateOne) check() error {
	if v, ok := muo.mutation.HashedVerificationToken(); ok {
		if err := member.HashedVerificationTokenValidator(v); err != nil {
			return &ValidationError{Name: "hashed_verification_token", err: fmt.Errorf(`ent: validator failed for field "Member.hashed_verification_token": %w`, err)}
		}
	}
	return nil
}

func (muo *MemberUpdateOne) sqlSave(ctx context.Context) (_node *Member, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   member.Table,
			Columns: member.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: member.FieldID,
			},
		},
	}
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Member.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, member.FieldID)
		for _, f := range fields {
			if !member.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != member.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.IsVerified(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: member.FieldIsVerified,
		})
	}
	if value, ok := muo.mutation.VerificationExpiry(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: member.FieldVerificationExpiry,
		})
	}
	if value, ok := muo.mutation.HashedVerificationToken(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBytes,
			Value:  value,
			Column: member.FieldHashedVerificationToken,
		})
	}
	if value, ok := muo.mutation.VerificationTokenExpiry(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: member.FieldVerificationTokenExpiry,
		})
	}
	_node = &Member{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{member.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
