// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/ymsg19/sfc-guardbot/ent/member"
	"github.com/ymsg19/sfc-guardbot/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	memberFields := schema.Member{}.Fields()
	_ = memberFields
	// memberDescDiscordUID is the schema descriptor for discord_uid field.
	memberDescDiscordUID := memberFields[0].Descriptor()
	// member.DiscordUIDValidator is a validator for the "discord_uid" field. It is called by the builders before save.
	member.DiscordUIDValidator = memberDescDiscordUID.Validators[0].(func(string) error)
	// memberDescEmail is the schema descriptor for email field.
	memberDescEmail := memberFields[1].Descriptor()
	// member.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	member.EmailValidator = func() func(string) error {
		validators := memberDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// memberDescIsVerified is the schema descriptor for is_verified field.
	memberDescIsVerified := memberFields[2].Descriptor()
	// member.DefaultIsVerified holds the default value on creation for the is_verified field.
	member.DefaultIsVerified = memberDescIsVerified.Default.(bool)
	// memberDescVerificationExpiry is the schema descriptor for verification_expiry field.
	memberDescVerificationExpiry := memberFields[3].Descriptor()
	// member.DefaultVerificationExpiry holds the default value on creation for the verification_expiry field.
	member.DefaultVerificationExpiry = memberDescVerificationExpiry.Default.(func() time.Time)
	// memberDescHashedVerificationToken is the schema descriptor for hashed_verification_token field.
	memberDescHashedVerificationToken := memberFields[4].Descriptor()
	// member.HashedVerificationTokenValidator is a validator for the "hashed_verification_token" field. It is called by the builders before save.
	member.HashedVerificationTokenValidator = memberDescHashedVerificationToken.Validators[0].(func([]byte) error)
	// memberDescVerificationTokenExpiry is the schema descriptor for verification_token_expiry field.
	memberDescVerificationTokenExpiry := memberFields[5].Descriptor()
	// member.DefaultVerificationTokenExpiry holds the default value on creation for the verification_token_expiry field.
	member.DefaultVerificationTokenExpiry = memberDescVerificationTokenExpiry.Default.(func() time.Time)
}
